### PR TITLE
Sierra

### PR DESCRIPTION
**Pull request by selamberson**
The changes in this branch are needed to get sierra versions 5.X to build and run with yogimpi.  Commits a9bf7ae and de7576f are the most "surprising" and are probably the most important changes for everyone to understand.

Before merging this branch, we need to field test the branch with current Helios and Kestrel.  I have Kestrel working on my workstation with gcc and both openmpi and mpich backends.  I recommend rebuilding avtools in addition to the final products as some of the function signatures will have changed.

@bpittman, let me know when you have enough infrastructure in place for me to run Jenkins and ATS, and I'll run those.

### CODE REVIEW

**Comment by rtrigg** [comment]
I built with intel and gcc on rhel7 with mpich and all system tests pass. I also built some third party solvers against this and those tests passed, so I'm pretty happy in that regard.

I haven't done any large-scale testing yet, but I can do that next week if you want. Alternatively, I'm okay with approving this after you or @bpittman does that testing.

I'm going to be out Fri-Wed, but if you ping me on here I'll see it and respond.

**Comment by selamberson** [comment]
@rtrigg, thanks.  I'd say approve it whenever you are comfortable with it.  The changes are significant enough that I don't want to merge it until we have run our ATS with it.  We did go ahead and tag it v1.4.0rc1 though so @bpittman doesn't need to rename all his VMs and such if we don't find any problems.

**Comment by selamberson** [comment]
@rtrigg and @bpittman, I have made progress on my yogimpi+sierra work.  I have a new rc to test.  Please test v1.4.0rc2 and let me know if it works for you.  If it works, please "approve" this pull request so github will let me merge it.

**Comment by selamberson** [comment]
@rtrigg and @bpittman, the Kestrel ATS on v1.4.0rc2 indicates that rc2 is ready from my point of view.  Can you two please look at the merge request, do whatever testing you need to do, and approve the pull request if it is ready so github will let me merge it.

**Comment by rtrigg** [comment]
system tests are passing, I'm happy. I converted the README to README.md a while back, and added a change for make dist

**Review by rtrigg — APPROVED** [review]
system tests are passing, I'm happy. I converted the README to README.md a while back, so I added a change for make dist

**Comment by rtrigg** [comment]
it really looks like I broke the CI with my update, but I swear I didn't :) I think this is an issue with a change to oneAPI; I'll look into it and report back

**Review by bpittman — APPROVED** [review]

**Pull request merged**
